#include <windows.h>
#include <string>
#include <cmath>
#include <format>
#include <vector>
#include <map>
#include <winternl.h>
#include <stdio.h>
#include <tchar.h>
#include <psapi.h>
#include <tlhelp32.h>
